language: objective-c

osx_image: xcode10.3
env:
  matrix:
    - TEST_SDK=iphonesimulator12.4 OS=12.4 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.4 OS=12.4 NAME='iPhone 7'
before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project StickyLayout.xcodeproj -scheme StickyLayout -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
